# --- Some useful functions for microbiome analysis

ggvis_taxa_plot = function(physeq, x_axis_var, taxa_level, interactive=FALSE) {
  # this is a function that takes a phyloseq object and creates an interactive plot
  # that can be viewed in RStudio or in your browser
  
  require(ggvis)
  
  if (!(x_axis_var %in% sample_variables(physeq))) {
    stop("Couldn't find sample variable in physeq object!")
  }
  
  if (!(taxa_level %in% rank_names(physeq))) {
    stop("Couldn't find taxa level in physeq object!")
  }
  
  
  # ---to format the tooltip correctly
  all_values <- function(x) {
    if(is.null(x)) return(NULL)
    show = x
    show$xmin_ = NULL
    show$xmax_ = NULL
    show$stack_upr_ = NULL
    show$stack_lwr_ = NULL
    show$Percent = round(100 * (x$stack_upr_ - x$stack_lwr_), 2)
    paste0(names(show), ": ", format(show), collapse = "<br />")
  }
  
  # --- need these as formulas for ggvis
  taxa_level = as.formula(paste0("~", taxa_level))
  x_axis_var = as.formula(paste0("~", x_axis_var))
  
  data_melt = psmelt(physeq)

  plot = data_melt %>% group_by_(taxa_level) %>% 
    ggvis(x = x_axis_var, y = ~Abundance, fill = taxa_level) %>%
    layer_bars()
  
  if (interactive) {
    plot = plot %>% add_tooltip(all_values, "hover")
  }  
  
  plot
}

ggvis_ord_plot = function(physeq, ord_obj, colour, interactive=FALSE){
  
  all_values <- function(x) {
    if(is.null(x)) return(NULL)
    paste0(names(x), ": ", format(x), collapse = "<br />")
    }
        
  # extract the scores from the ordination
  ord_data = plot_ordination(physeq, ord_obj, justDF = TRUE)
  
  # format for ggvis
  x = as.formula(paste0("~", colnames(ord_data)[1]))
  y = as.formula(paste0("~", colnames(ord_data)[2]))
  colour = as.formula(paste0("~", as.character(colour)))
  
  plot = ord_data %>% ggvis(x = x, y = y, strokeWidth := 0, fill = colour) %>%
    layer_points() 
  
  if (interactive) {
    plot = plot %>% add_tooltip(all_values, "hover")
  }
 
  plot
}


#  Colour Palettes --------------------------------------------------------
# generated by I want hue (http://tools.medialab.sciences-po.fr/iwanthue/)

intensePal1 = c("#105B1F","#F845B3","#4082D9","#8A2829","#DFAD47","#45356B","#F08C8D","#A4BF68","#9133A2","#8F82FF","#F485B5","#AF6C16","#E0277D","#814014")
fancyPal1 = c("#A6D9C6","#DEDA5E","#F0A4B5","#6CE4A4","#E8B26D","#C8B7E7","#ACE376","#5BDEEA","#CCD184","#58EDD2","#CECCDA","#92CDE5","#A6DD9E","#69CEBE")

large22 = c("#75CADB","#D1693C","#87DB49","#D089D3","#5E8859","#B97886","#7895D5","#D79D36","#C7D58F","#D4D64A","#6AD9B7","#D0BCD4","#D5A47D","#69D37D","#4B868E","#D25E63","#C3D3C1","#748E30","#806B94","#936837","#827B72","#CF6294")
large23 = c("#DA6056","#6EDB5C","#82B5D8","#E2B93D","#6F805B","#CE7DCA","#61CFB1","#CEBAB4","#8F6687","#C3D76F","#51913E","#CA7932","#D9AD7C","#D16485","#89852E","#588086","#A36854","#BED7A0","#B8DB38","#D9ACD4","#67DB92","#758ACA","#8DD5D7")
large37 = c("#F680A0","#7BF12D","#26C4BC","#C48001","#8195ED","#646657","#FAEBEC","#EAE979","#23AC52","#F776DD","#718805","#A44C2A","#7A5E95","#3B7239","#3D91C1","#A0F8C3","#E7E5AE","#18737B","#DCD125","#F06F21","#B84554","#F49A8A","#30F264","#3CCAE9","#7F5560","#DD9CFA","#4D9719","#85F8FF","#605E7A","#CDB6FE","#77FDE4","#CCDEF8","#2687D5","#D061B4","#D25987","#2FC354","#91E507")
large14 = c("#95D997","#CD8ACE","#CB6F3F","#C2D744","#62837D","#867D44","#CA6374","#7EA0CF","#D6BDA7","#7CD5CF","#73DD5D","#D2AB44","#519143","#916E8D")

pal5 = c("#D33606","#1762B1","#36720F","#2BB3A7","#D29C44")
pal4 = c("#FF6730","#1A87C3","#096F36","#B31589")
pal12 = c("#D50869","#68B978","#3362CA","#F67419","#DC70F1","#FE8976","#AC88C1","#FB160E","#128471","#E39946","#8693F0","#A51053")

fancy5 = c("#CDBCDC","#E0CF61","#7DDCCA","#EDA884","#ABDF8A")
fancy4 = c("#4DC28E","#F496D3","#E5C848","#08C9E8")

intense4 = c("#BB4A53","#58955B","#966BB3","#AD8031")
intense14 = c("#6D3F86","#6EAC38","#CE4F34","#67A2BD","#CB983E","#CC51D7","#436539","#D95C80","#5BAF7E","#7F7DDA","#7B5724","#656284","#CC64B3","#8C404D")

taxa_colour_30 = c("#C36768","#77D265","#7997BA","#C9CA49","#C5813B","#BF6D93","#7AD2BA","#CBBDA4","#6D8D47","#62C98B","#9CD0E0","#D7AA3E","#DAB1D1","#5D8962","#92705E","#CD7FCD","#D85F47","#7D8BCD","#557369","#5D6A8B","#619A2D","#4EABD9","#8F608F","#8E7D3A","#9B99EC","#4E9D9C","#CDDB94","#DB9A80","#9A989C","#EE9CCA")

displayPal = function(pal) {
  # function to print out a colour palette that's stored as a character vector
  n = length(pal)
  image(1:n, 1, as.matrix(1:n), col = pal, 
        xlab = "", ylab = "", xaxt = "n", yaxt = "n", 
        bty = "n")
}

veganotu = function(physeq) {
  require("vegan")
  OTU = otu_table(physeq)
  if (taxa_are_rows(OTU)) {
    OTU = t(OTU)
  }
  return(as(OTU, "matrix"))
}








